### ISSUE TITLE
Ability to link announcements to calendar assignments

### ISSUE THREAD

**Issue by rpkenney** [nfoster1492/ClassMateBot-1#6]

**Comment by brwali** [comment]
What does this mean again? Is this saying that if the deadline is within a certain period of time then the bot should send an announcement to everyone?

**Comment by brwali** [comment]
A discussion was held on discord and this command will check the calendar every day to see if there are any events that are due on that day, if there are then ping everyone in the general chat that those events are due. This functionality was verified by another dev but still needs tests written.
