### ISSUE TITLE
Ability for student to query their grade based on assignment

### ISSUE THREAD

**Issue by rpkenney** [nfoster1492/ClassMateBot-1#9]

**Comment by nfoster1492** [comment]
This command allows students to view their grade for a specific assignment.

Written in grades.py

We discussed many different ways of using the database to store the information for assignments and points values. We finally decided on the current method of using an assignments table to store the name and points values and a grades table to store the assignment ID and the actual percentage grade. Now students can view their personal grades on assignments.
